targets:
  $default:
    builders:
      cached:
        generate_for:
          - test/integration/**

builders:
  cached:
    import: "package:persistant_cached/persistant_cached.dart"
    builder_factories: ["cachedBuilder"]
    build_extensions: { ".dart": [".cached.dart"] }
    auto_apply: dependents
    build_to: source
