name: persistant_cached
description: Dart package with build-in code generation. Simplifies and speedup creation of cache mechanism for dart classes.
version: 1.6.2
repository: https://github.com/Get-Flave/cached
issue_tracker: https://github.com/Get-Flave/cached/issues
homepage: https://github.com/Get-Flave/cached
documentation: https://github.com/Get-Flave/cached/blob/master/packages/cached/README.md

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^5.2.0
  build: ^2.3.0
  cached_annotation: ^1.6.0
  collection: ^1.16.0
  meta: ^1.7.0
  source_gen: ^1.2.2
  source_helper: ^1.3.2

dev_dependencies:
  async: ^2.9.0
  build_runner: ^2.1.11
  path: ^1.8.2
  source_gen_test: ^1.0.3
  test: ^1.21.1
  linteo: ^1.0.1
