name: cached_annotation
description: Annotation package for cached lib
version: 1.6.0
repository: https://github.com/Get-Flave/cached
issue_tracker: https://github.com/Get-Flave/cached/issues
homepage: https://github.com/Get-Flave/cached
documentation: https://github.com/Get-Flave/cached/blob/master/packages/cached/README.md

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  linteo: ^1.0.1
